import cv2
img1= cv2.imread('fingerprint.jpg')
img2= cv2.imread('fingerwithnoise.png')
sift = cv2.SIFT_create()
kp1, des1= sift.detectAndCompute(img1, None)
kp2, des2 = sift.detectAndCompute(img2, None)
index_params=dict(algorithm=0)
search_param = dict()
flann  = cv2.FlannBasedMatcher(index_params, search_param)
matches = flann.knnMatch(des1, des2, k=2)
result = cv2.drawMatchesKnn(img1,kp1,img2, kp2,matches, None)
cv2.imshow("img1", img1)
cv2.imshow("img2", img2)
cv2.imshow("result", result)
cv2.waitKey()
cv2.destroyAllWindows()